### PR TITLE
Updated Readme

### PR DESCRIPTION
**Pull request by adityathakurxd**
Make a presentable README.md #2

Please check this PR and let me know if any changes are required.

### CODE REVIEW

**Comment by nayakastha** [comment]
@adityathakurxd  It's great. Thanks a lot for your contribution 🍻

**Comment by adityathakurxd** [comment]
Thank you :)

**Comment by nayakastha** [comment]
@adityathakurxd  Do check-out if you can add any other feature to any of my projects. 😄

**Comment by adityathakurxd** [comment]
Sure. I'll have a look. 
Thank you for this opportunity.

**Pull request merged**
